USE aquario;

DROP TABLE IF EXISTS fornece;
DROP TABLE IF EXISTS fornecedor;
DROP TABLE IF EXISTS estoque;
DROP TABLE IF EXISTS consome;
DROP TABLE IF EXISTS cuida;
DROP TABLE IF EXISTS biologo;
DROP TABLE IF EXISTS contem;
DROP TABLE IF EXISTS animais;
DROP TABLE IF EXISTS tanques;
DROP TABLE IF EXISTS compra;
DROP TABLE IF EXISTS funcionario;
DROP TABLE IF EXISTS alimento;
DROP TABLE IF EXISTS especie;
DROP TABLE IF EXISTS setores;
DROP TABLE IF EXISTS bilhete;
DROP TABLE IF EXISTS visitante;
